application:
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  database_name: "newsletter"
email_client:
  base_url: "http://localhost"
  sender_email: "test@gmail.com"
  # We are only setting the development value,
  # we'll deal with the production token outside of version control
  # (given that it's a sensitive secret!)
  authorisation_token: "my-secret-token"
  timeout_milliseconds: 10000
